"""initial schema

Revision ID: d6c1427856bf
Revises:
Create Date: 2026-06-04 12:54:11.135685

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d6c1427856bf"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("category_id", name=op.f("pk_categories")),
    )
    op.create_table(
        "locations",
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=255), nullable=False),
        sa.Column("state_region", sa.String(length=255), nullable=True),
        sa.Column("country", sa.String(length=255), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("location_id", name=op.f("pk_locations")),
    )
    op.create_table(
        "users",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    op.create_table(
        "keywords",
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("keyword_name", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
            name=op.f("fk_keywords_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("keyword_id", name=op.f("pk_keywords")),
    )
    with op.batch_alter_table("keywords", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_keywords_category_id"), ["category_id"], unique=False
        )

    op.create_table(
        "programs",
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("creator_user_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("location_id", sa.Integer(), nullable=False),
        sa.Column("program_name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("banner_image_url", sa.String(length=500), nullable=True),
        sa.Column("start_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_datetime", sa.DateTime(timezone=True), nullable=False),
        sa.Column("max_volunteers", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft", "open", "full", "closed", "cancelled", name="programstatus"
            ),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["categories.category_id"],
            name=op.f("fk_programs_category_id_categories"),
        ),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.user_id"],
            name=op.f("fk_programs_creator_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.location_id"],
            name=op.f("fk_programs_location_id_locations"),
        ),
        sa.PrimaryKeyConstraint("program_id", name=op.f("pk_programs")),
    )
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_programs_category_id"), ["category_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_programs_creator_user_id"), ["creator_user_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_programs_location_id"), ["location_id"], unique=False
        )

    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=255), nullable=False),
        sa.Column("last_name", sa.String(length=255), nullable=False),
        sa.Column("date_of_birth", sa.DateTime(timezone=True), nullable=True),
        sa.Column("profile_image_url", sa.String(length=500), nullable=True),
        sa.Column("occupation", sa.String(length=255), nullable=True),
        sa.Column("goal_text", sa.String(length=1000), nullable=True),
        sa.Column("location_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.location_id"],
            name=op.f("fk_user_profiles_location_id_locations"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_user_profiles_user_id_users")
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_user_profiles")),
    )
    op.create_table(
        "forum_posts",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.user_id"],
            name=op.f("fk_forum_posts_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.program_id"],
            name=op.f("fk_forum_posts_program_id_programs"),
        ),
        sa.PrimaryKeyConstraint("post_id", name=op.f("pk_forum_posts")),
    )
    with op.batch_alter_table("forum_posts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forum_posts_author_user_id"),
            ["author_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forum_posts_program_id"), ["program_id"], unique=False
        )

    op.create_table(
        "program_bookmarks",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column(
            "bookmarked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.program_id"],
            name=op.f("fk_program_bookmarks_program_id_programs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_program_bookmarks_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "program_id", name=op.f("pk_program_bookmarks")
        ),
    )
    op.create_table(
        "program_keywords",
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keywords.keyword_id"],
            name=op.f("fk_program_keywords_keyword_id_keywords"),
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.program_id"],
            name=op.f("fk_program_keywords_program_id_programs"),
        ),
        sa.PrimaryKeyConstraint(
            "program_id", "keyword_id", name=op.f("pk_program_keywords")
        ),
    )
    op.create_table(
        "program_participations",
        sa.Column("participation_id", sa.Integer(), nullable=False),
        sa.Column("program_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "participation_status",
            sa.Enum(
                "pending",
                "approved",
                "rejected",
                "withdrawn",
                name="participationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "joined_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["program_id"],
            ["programs.program_id"],
            name=op.f("fk_program_participations_program_id_programs"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_program_participations_user_id_users"),
        ),
        sa.PrimaryKeyConstraint(
            "participation_id", name=op.f("pk_program_participations")
        ),
    )
    with op.batch_alter_table("program_participations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_program_participations_program_id"),
            ["program_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_program_participations_user_id"), ["user_id"], unique=False
        )

    op.create_table(
        "user_interests",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("keyword_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["keyword_id"],
            ["keywords.keyword_id"],
            name=op.f("fk_user_interests_keyword_id_keywords"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name=op.f("fk_user_interests_user_id_users")
        ),
        sa.PrimaryKeyConstraint(
            "user_id", "keyword_id", name=op.f("pk_user_interests")
        ),
    )
    op.create_table(
        "forum_comments",
        sa.Column("comment_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("author_user_id", sa.Integer(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["author_user_id"],
            ["users.user_id"],
            name=op.f("fk_forum_comments_author_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["forum_posts.post_id"],
            name=op.f("fk_forum_comments_post_id_forum_posts"),
        ),
        sa.PrimaryKeyConstraint("comment_id", name=op.f("pk_forum_comments")),
    )
    with op.batch_alter_table("forum_comments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_forum_comments_author_user_id"),
            ["author_user_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_forum_comments_post_id"), ["post_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("forum_comments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_comments_post_id"))
        batch_op.drop_index(batch_op.f("ix_forum_comments_author_user_id"))

    op.drop_table("forum_comments")
    op.drop_table("user_interests")
    with op.batch_alter_table("program_participations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_program_participations_user_id"))
        batch_op.drop_index(batch_op.f("ix_program_participations_program_id"))

    op.drop_table("program_participations")
    op.drop_table("program_keywords")
    op.drop_table("program_bookmarks")
    with op.batch_alter_table("forum_posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_forum_posts_program_id"))
        batch_op.drop_index(batch_op.f("ix_forum_posts_author_user_id"))

    op.drop_table("forum_posts")
    op.drop_table("user_profiles")
    with op.batch_alter_table("programs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_programs_location_id"))
        batch_op.drop_index(batch_op.f("ix_programs_creator_user_id"))
        batch_op.drop_index(batch_op.f("ix_programs_category_id"))

    op.drop_table("programs")
    with op.batch_alter_table("keywords", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_keywords_category_id"))

    op.drop_table("keywords")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    op.drop_table("locations")
    op.drop_table("categories")
    # ### end Alembic commands ###
